[tool.poetry]
name = "image-background-removal"
version = "0.1.0"
description = ""
authors = ["caots <honghoang1232@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.11,<3.14"
flask = "^3.1.0"
rembg = "^2.0.65"
pillow = "^11.2.1"
flask-dropzone = "^2.0.0"
onnxruntime = "^1.21.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
